# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SignalAnalyser_a02.ui'
#
# Created: Mon Sep 07 15:01:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 798)
        MainWindow.setMinimumSize(QtCore.QSize(529, 798))
        MainWindow.setMaximumSize(QtCore.QSize(692, 1016))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(43, 43, 43);\n"
"")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_btn = QtGui.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.load_btn.setObjectName("load_btn")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(161, 161, 161);\n"
"color: rgb(255, 255, 255);\n"
"padding:2px;")
        self.label.setObjectName("label")
        self.play_btn = QtGui.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(20, 45, 75, 23))
        self.play_btn.setObjectName("play_btn")
        self.ana_btn = QtGui.QPushButton(self.centralwidget)
        self.ana_btn.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.ana_btn.setObjectName("ana_btn")
        self.figure1 = WaveMplCanvas(self.centralwidget)
        self.figure1.setGeometry(QtCore.QRect(50, 120, 466, 171))
        self.figure1.setObjectName("figure1")
        self.plot_btn = QtGui.QPushButton(self.centralwidget)
        self.plot_btn.setGeometry(QtCore.QRect(105, 80, 75, 23))
        self.plot_btn.setObjectName("plot_btn")
        self.figure2 = GwtMplCanvas(self.centralwidget)
        self.figure2.setGeometry(QtCore.QRect(50, 310, 466, 171))
        self.figure2.setObjectName("figure2")
        self.atTimeSlider = QtGui.QSlider(self.centralwidget)
        self.atTimeSlider.setGeometry(QtCore.QRect(40, 530, 471, 19))
        self.atTimeSlider.setMaximum(99)
        self.atTimeSlider.setSingleStep(1)
        self.atTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.atTimeSlider.setObjectName("atTimeSlider")
        self.figure3 = SpectrumAtTimeMplCanvas(self.centralwidget)
        self.figure3.setGeometry(QtCore.QRect(50, 560, 461, 171))
        self.figure3.setObjectName("figure3")
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(240, 500, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 43, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.menubar.setPalette(palette)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setEnabled(False)
        self.menuFile.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setStyleSheet("background-color: rgb(73, 73, 73)\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_fifi/icon_fifics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFile.setIcon(icon)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuFile.setObjectName("menuFile")
        self.menuFiSig = QtGui.QMenu(self.menubar)
        self.menuFiSig.setAutoFillBackground(False)
        self.menuFiSig.setStyleSheet("background-color: rgb(73, 73, 73);\n"
"border-right-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.menuFiSig.setObjectName("menuFiSig")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_wav = QtGui.QAction(MainWindow)
        self.actionOpen_wav.setObjectName("actionOpen_wav")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen_wav_2 = QtGui.QAction(MainWindow)
        self.actionOpen_wav_2.setObjectName("actionOpen_wav_2")
        self.actionClose_2 = QtGui.QAction(MainWindow)
        self.actionClose_2.setCheckable(False)
        self.actionClose_2.setObjectName("actionClose_2")
        self.menuFiSig.addAction(self.actionOpen_wav_2)
        self.menuFiSig.addAction(self.actionClose_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFiSig.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.load_btn, QtCore.SIGNAL("clicked()"), MainWindow.openFileDialog)
        QtCore.QObject.connect(self.actionClose_2, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionOpen_wav_2, QtCore.SIGNAL("triggered()"), MainWindow.openFileDialog)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL("fileloaded(QString)"), self.label.setText)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL("fileloaded(QString)"), MainWindow.flashStatusBar)
        QtCore.QObject.connect(self.play_btn, QtCore.SIGNAL("clicked()"), MainWindow.playAudio)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL("fileloaded(QString)"), MainWindow.setAudioFile)
        QtCore.QObject.connect(self.ana_btn, QtCore.SIGNAL("clicked()"), MainWindow.analys)
        QtCore.QObject.connect(self.plot_btn, QtCore.SIGNAL("clicked()"), MainWindow.plot)
        QtCore.QObject.connect(self.atTimeSlider, QtCore.SIGNAL("valueChanged(int)"), self.figure3.updateAtTime)
        QtCore.QObject.connect(self.atTimeSlider, QtCore.SIGNAL("valueChanged(int)"), self.lcdNumber.display)
        QtCore.QObject.connect(self.atTimeSlider, QtCore.SIGNAL("valueChanged(int)"), self.figure2.updateAtTime)
        QtCore.QObject.connect(self.atTimeSlider, QtCore.SIGNAL("valueChanged(int)"), self.figure1.updateAtTime)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.load_btn.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "no .wav file", None, QtGui.QApplication.UnicodeUTF8))
        self.play_btn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.ana_btn.setText(QtGui.QApplication.translate("MainWindow", "Analys", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_btn.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiSig.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_wav.setText(QtGui.QApplication.translate("MainWindow", "Open(.wav)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_wav_2.setText(QtGui.QApplication.translate("MainWindow", "Open(.wav)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_2.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

from FiSig.MplCanvas import SpectrumAtTimeMplCanvas, WaveMplCanvas, GwtMplCanvas
